### ISSUE TITLE
dnf module install python2 fails

### ISSUE THREAD

**Issue by alexxa** [modularity-modules/python2#1]
Error: 
 Problem: conflicting requests
 - nothing provides python2-tkinter = 2.7.13-18.module_9283ad27 needed by python2-tools-2.7.13-18.module_9283ad27.x86_64

**Comment by alexxa** [comment]
@KarstenHopp

**Comment by torsava** [comment]
@alexxa A fix for this issue just finished building, could you please check the installability of the module now?

**Comment by alexxa** [comment]
@torsava it passed today.
