### ISSUE TITLE
Sync content with python3-ecosystem

### ISSUE THREAD

**Issue by ncoghlan** [modularity-modules/python2#3]
@mhlavink Are you planning to submit a Python 2.7 ecosystem module update similar to the one you did for Python 3?

**Comment by mhlavink** [comment]
@ncoghlan yes, that's my plan

**Comment by torsava** [comment]
@ncoghlan I don't think we should *sync* content with python3-ecosystem necessarily. Right now the ecosystem modules are for supporting Python software in other modules, so if we only need a Python 3 version of a dependency but not a Python 2 version, we shouldn't include it here.

**Comment by ncoghlan** [comment]
Aye, the included-for-specific-other-modules parts can potentially be left out of the Python 2 ecosystem if those modules don't offer Python 2 builds, but we should still offer some of the key common dependencies for hybrid Python 2/3 applications (e.g. requests, PyOpenSSL)

**Comment by torsava** [comment]
@ncoghlan Agreed! However, right now Platform-Python takes priority so I haven't gotten around to it.

**Comment by mhlavink** [comment]
I did first round of changes, similar to p3-ecosystem. It's not a sync per se, but checked dependencies of this module, other modules and "to be expected" modules. There will be another portion of changes, so I'm keeping this open for now. First, I need working compose, because that's what I use for testing and dependency checking.

**Comment by ignatenkobrain** [comment]
@mhlavink any PRs?

I had to add some package yesterday here and the diff was looking insane to me.

**Comment by mhlavink** [comment]
@ignatenkobrain none atm

Could you be more specific? This was almost exclusively p-request with its dependencies (it has a few). Should not be insane, nor halloweeny

**Comment by ncoghlan** [comment]
@mhlavink I'm guessing @ignatenkobrain might be referring to the fact that the RPM api listing python2-ecosystem is now substantially *longer* than the list in python3-ecosystem. Current extra packages only in the Python 2 ecosystem module (after accounting for the differences in prefix):

```
dbus-python-devel
python-dateutil-doc
python-qrcode-core
python2-asn1crypto
python2-augeas
python2-configparser
python2-crypto
python2-dateutil
python2-dbus
python2-gssapi
python2-ipaddress
python2-kdcproxy
python2-netaddr
python2-netifaces
python2-pyusb
python2-qrcode
python2-typing
```

**Comment by mhlavink** [comment]
From packages you listed, I've added only python2-asn1crypto and python2-ipaddress, both p2-requests requirements. For other packages (that I did not add there) it seems they are mostly freeipa requirements, as written in their respective rationale.

**Comment by torsava** [comment]
I talked with @ignatenkobrain and he was confused by the name of this issue including the word "sync". As discussed earlier, the primary purpose of the ecosystem modules in F27 modular server is to house shared Python dependencies of the various other modules, only in the version they are required in (Python or Python 3, not necessarily both).

A content sync between the Python 2 and Python 3 ecosystem modules is only planned for the future beyond F27 where the modules will be for direct user consumption. Therefore I'm closing the issue for now.
